---
  - name: Configurar aplicação Java
    hosts: app01
    user: vagrant
    become: true
    vars:
      dbhost: "db01"
      dbname: "notes_db"
      dbusername: "notes"
      dbpassword: "devops"
    tasks:
      - name: Adicionar entradas no /etc/hosts
        lineinfile:
          dest: /etc/hosts
          line: "{{ item }}"
          state: present
        with_items:
          - "192.168.33.2 control-node"
          - "192.168.33.3 app01"
          - "192.168.33.4 db01"
      - name: Instalando o GIT
        yum:
         name:
          - git
         state: latest    
      - name: Adicionar usuário do APP
        user:
          name: app
          comment: "Usuário da aplicação"
          uid: 500
      - name: Instalar o Maven
        yum:
          name: maven
          state: latest
      - name: Instalar o Java
        yum:
          name: java-1.8.0-openjdk
          state: latest
      - name: Criação dos diretórios do APP
        file:
         path: /opt/notes   
         state: directory
         owner: app
         group: app

      - name: Clone da aplicação - Notes APP
        git:
          repo: "https://github.com/callicoder/spring-boot-mysql-rest-api-tutorial.git"
          dest: "/opt/notes"
          clone: yes
          force: yes
          version: "master"
      - name: Confirgurar arquivo de propriedades do APP para conexão com o banco de dados
        template:
          src: "application.properties"
          dest: "/opt/notes/src/main/resources/application.properties"

      - name: Gerar pacote da aplicação
        command: mvn -f /opt/notes/pom.xml package
        become_user: app
        environment:
         PATH: "/opt/apache-maven-3.9.10/bin:{{ ansible_env.PATH }}"
      #Executei o comando manualmente para verificar a versão do plugin
      #mvn org.codehaus.mojo:exec-maven-plugin:3.1.0:help
      - name: Registar versão atual do pacote
        shell: 
         cmd: mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' exec:exec
         chdir: /opt/notes
        register: app_version

      - name: Configurar serviço do Systemd
        template: 
          src: etc/systemd/system/notes.service
          dest: /etc/systemd/system/notes.service
          owner: root
          group: root
          mode: '0600'
        notify: reload daemon
      - name: Iniciar serviço notes
        service:
         name: notes
         state: restarted
    roles:
      - configuracao-default-so
    handlers:
    - name: reload app
      systemd:
        state: restarted
        daemon_reload: yes 
        name: notes
    - name: reload daemon
      systemd:
        daemon_reload: yes
