---
- name: Configurar base de dados MySQL
  hosts: db01
  user: vagrant
  become: true
  vars_files:
    - vars/main.yml
  vars:
    mysql_client: mysql
    dbname: "db01"
    dbusername: "root"
    dbpassword: "devops"
  tasks:
    - name: Configurar o host ansible
      lineinfile: line {{item}} path=/etc/hosts
      with_items:
        - 192.168.1.2 control-node
        - 192.168.1.3 app01
        - 192.168.1.4 db01

  roles:
  - configuracao-default-so
  - role: geerlingguy.mysql
 