- name: Upgrade dos pacotes do sistema CentOS
  yum:
   name: "*"
   state: latest
   update_cache: yes

- name: Instalar pacotes adicionais
  yum:
    name:
      - git
      - wget
      - curl
      - net-tools
      - nano
    state: latest