Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.hostname = "app01"
  config.vm.network "private_network", ip: "192.168.33.3"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.provision "shell", path: "provision.sh"
  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "512"
   end

end
