version: "3"
services:
  redis-server:
    image: redis:latest
    container_name: redis-server
  node-app:
    build: .
    container_name: node-app
    ports:
      - "8080:8081"
    depends_on:
      - redis-server